environment: false
frontend_path: http://localhost:3000
oauth_redirect_path: /auth-redirect
port: :4000
cors:
  - http://localhost:3000
jwt_secret: 124567
db: user:pass@tcp(domain.com:3306)/db_name?charset=utf8mb4&parseTime=True&loc=Local
oauth_endpoint: https://login.microsoftonline.com/XXXXXXXXXXXXXX/v2.0
oauth_client_id: XXXXXXXX
oauth_client_secret: XXXXXXXX